# win32-clang-msvc: QMAKE_CFLAGS += -msse4.1 -maes -mavx2 -msse2 -mssse3 -mpclmul # -march=native

# DISTFILES +=
#     ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S

set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

set(SODIUM_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/fe_25_5/base.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/fe_25_5/base2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/fe_25_5/constants.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/fe_25_5/fe.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/fe_51/base.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/fe_51/base2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/fe_51/constants.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/fe_51/fe.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-compress-avx2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-compress-sse41.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-compress-ssse3.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-load-avx2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-load-sse2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-load-sse41.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/poly1305/donna/poly1305_donna.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/poly1305/donna/poly1305_donna64.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/poly1305/onetimeauth_poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/poly1305/sse2/poly1305_sse2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2-core.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2-encoding.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/blake2b-long.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/blamka-round-avx2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/blamka-round-avx512f.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/blamka-round-ref.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/blamka-round-ssse3.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/ref10/x25519_ref10.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/consts.S
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/consts_namespace.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/curve25519_sandy2x.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/fe.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/fe51.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/fe51_mul.S
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/fe51_namespace.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/fe51_nsquare.S
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/fe51_pack.S
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/ladder.S
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/ladder.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/ladder_namespace.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/sandy2x.S
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/scalarmult_curve25519.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_shorthash/siphash24/ref/shorthash_siphash_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_sign/ed25519/ref10/sign_ed25519_ref10.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/dolbeau/chacha20_dolbeau-avx2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/dolbeau/chacha20_dolbeau-ssse3.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/dolbeau/u0.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/dolbeau/u1.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/dolbeau/u4.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/dolbeau/u8.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/ref/chacha20_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/stream_chacha20.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/ref/salsa20_ref.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/stream_salsa20.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6/salsa20_xmm6.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6int/salsa20_xmm6int-avx2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6int/salsa20_xmm6int-sse2.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6int/u0.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6int/u1.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6int/u4.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6int/u8.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/core.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_aead_aes256gcm.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_aead_chacha20poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_aead_xchacha20poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_auth.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_auth_hmacsha256.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_auth_hmacsha512.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_auth_hmacsha512256.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_box.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_box_curve25519xchacha20poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_box_curve25519xsalsa20poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_core_ed25519.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_core_hchacha20.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_core_hsalsa20.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_core_ristretto255.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_core_salsa20.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_core_salsa2012.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_core_salsa208.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_generichash.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_generichash_blake2b.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_hash.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_hash_sha256.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_hash_sha512.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_kdf.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_kdf_blake2b.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_kx.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_onetimeauth.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_onetimeauth_poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_pwhash.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_pwhash_argon2i.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_pwhash_argon2id.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_pwhash_scryptsalsa208sha256.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_scalarmult.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_scalarmult_curve25519.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_scalarmult_ed25519.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_scalarmult_ristretto255.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_secretbox.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_secretbox_xchacha20poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_secretbox_xsalsa20poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_secretstream_xchacha20poly1305.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_shorthash.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_shorthash_siphash24.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_sign.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_sign_ed25519.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_sign_edwards25519sha512batch.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_stream.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_stream_chacha20.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_stream_salsa20.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_stream_salsa2012.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_stream_salsa208.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_stream_xchacha20.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_stream_xsalsa20.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_verify_16.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_verify_32.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/crypto_verify_64.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/export.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/randombytes.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/randombytes_internal_random.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/randombytes_sysrandom.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/runtime.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/sodium_version.h
    ${CMAKE_CURRENT_LIST_DIR}/include/sodium/utils.h
    ${CMAKE_CURRENT_LIST_DIR}/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_aead/xchacha20poly1305/sodium/aead_xchacha20poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_auth/crypto_auth.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_auth/hmacsha256/auth_hmacsha256.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_auth/hmacsha512/auth_hmacsha512.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_auth/hmacsha512256/auth_hmacsha512256.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_box/crypto_box.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_box/crypto_box_easy.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_box/crypto_box_seal.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_box/curve25519xchacha20poly1305/box_curve25519xchacha20poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_box/curve25519xchacha20poly1305/box_seal_curve25519xchacha20poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/core_ed25519.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/core_ristretto255.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/ed25519/ref10/ed25519_ref10.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/hchacha20/core_hchacha20.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/hsalsa20/core_hsalsa20.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/hsalsa20/ref2/core_hsalsa20_ref2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_core/salsa/ref/core_salsa_ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/generichash_blake2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-compress-avx2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-compress-ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-compress-sse41.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-compress-ssse3.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/blake2b-ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/blake2b/ref/generichash_blake2b.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_generichash/crypto_generichash.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_hash/crypto_hash.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_hash/sha256/cp/hash_sha256_cp.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_hash/sha256/hash_sha256.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_hash/sha512/cp/hash_sha512_cp.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_hash/sha512/hash_sha512.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_kdf/blake2b/kdf_blake2b.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_kdf/crypto_kdf.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_kx/crypto_kx.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/crypto_onetimeauth.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/poly1305/donna/poly1305_donna.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/poly1305/onetimeauth_poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_onetimeauth/poly1305/sse2/poly1305_sse2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2-core.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2-encoding.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2-fill-block-avx2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2-fill-block-avx512f.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2-fill-block-ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2-fill-block-ssse3.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/argon2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/blake2b-long.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/pwhash_argon2i.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/argon2/pwhash_argon2id.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/crypto_pwhash.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/scryptsalsa208sha256/crypto_scrypt-common.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/scryptsalsa208sha256/nosse/pwhash_scryptsalsa208sha256_nosse.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/scryptsalsa208sha256/pwhash_scryptsalsa208sha256.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/scryptsalsa208sha256/scrypt_platform.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_pwhash/scryptsalsa208sha256/sse/pwhash_scryptsalsa208sha256_sse.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/crypto_scalarmult.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/ref10/x25519_ref10.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/curve25519_sandy2x.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/fe51_invert.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/sandy2x/fe_frombytes_sandy2x.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/curve25519/scalarmult_curve25519.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/ed25519/ref10/scalarmult_ed25519_ref10.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_scalarmult/ristretto255/ref10/scalarmult_ristretto255_ref10.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_secretbox/crypto_secretbox.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_secretbox/crypto_secretbox_easy.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_secretbox/xsalsa20poly1305/secretbox_xsalsa20poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_secretstream/xchacha20poly1305/secretstream_xchacha20poly1305.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_shorthash/crypto_shorthash.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_shorthash/siphash24/ref/shorthash_siphash24_ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_shorthash/siphash24/ref/shorthash_siphashx24_ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_shorthash/siphash24/shorthash_siphash24.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_shorthash/siphash24/shorthash_siphashx24.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_sign/crypto_sign.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_sign/ed25519/ref10/keypair.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_sign/ed25519/ref10/obsolete.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_sign/ed25519/ref10/open.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_sign/ed25519/ref10/sign.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_sign/ed25519/sign_ed25519.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/dolbeau/chacha20_dolbeau-avx2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/dolbeau/chacha20_dolbeau-ssse3.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/ref/chacha20_ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/chacha20/stream_chacha20.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/crypto_stream.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/ref/salsa20_ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/stream_salsa20.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6/salsa20_xmm6.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6int/salsa20_xmm6int-avx2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa20/xmm6int/salsa20_xmm6int-sse2.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa2012/ref/stream_salsa2012_ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa2012/stream_salsa2012.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa208/ref/stream_salsa208_ref.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/salsa208/stream_salsa208.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/xchacha20/stream_xchacha20.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_stream/xsalsa20/stream_xsalsa20.c
    ${CMAKE_CURRENT_LIST_DIR}/crypto_verify/sodium/verify.c
    ${CMAKE_CURRENT_LIST_DIR}/randombytes/internal/randombytes_internal_random.c
    ${CMAKE_CURRENT_LIST_DIR}/randombytes/randombytes.c
    ${CMAKE_CURRENT_LIST_DIR}/randombytes/sysrandom/randombytes_sysrandom.c
    ${CMAKE_CURRENT_LIST_DIR}/sodium/codecs.c
    ${CMAKE_CURRENT_LIST_DIR}/sodium/core.c
    ${CMAKE_CURRENT_LIST_DIR}/sodium/runtime.c
    ${CMAKE_CURRENT_LIST_DIR}/sodium/sodium_version.c
    ${CMAKE_CURRENT_LIST_DIR}/sodium/utils.c
)

if (EXTRACHAIN_STATIC_BUILD)
    add_definitions(-DSODIUM_STATIC)
    add_library(sodium OBJECT
        ${SODIUM_SOURCES}
    )
else()
    add_library(sodium SHARED
        ${SODIUM_SOURCES}
    )
endif()

target_include_directories(sodium PUBLIC ${CMAKE_CURRENT_LIST_DIR}/include ${CMAKE_CURRENT_LIST_DIR}/include/sodium ${CMAKE_CURRENT_LIST_DIR}/include/private)
set_property(TARGET sodium PROPERTY POSITION_INDEPENDENT_CODE 1)
message("--- Sodium ---")
message(${CMAKE_CURRENT_LIST_DIR})

